### ISSUE TITLE
no module named clip

### ISSUE THREAD

**Issue by DeXtmL** [ventusff/improved-nerfmm#2]
Trying to experiment with perceptual model, upon training it says:

```
Traceback (most recent call last):
  File "train.py", line 490, in <module>
    main_function(config)
  File "train.py", line 224, in main_function
    perceptual_net = CLIP_for_Perceptual()
  File "/content/improved-nerfmm/models/perceptual_model.py", line 65, in __init__
    import clip
ModuleNotFoundError: No module named 'clip'
```

**Comment by DeXtmL** [comment]
installation is done with:
`pip install numpy pyyaml addict imageio imageio-ffmpeg scikit-image tqdm tensorboardX "pytorch3d>=0.3.0" opencv-python transformers`

**Comment by ventusff** [comment]
Hi @DeXtmL,
The clip model is in the implementation of OPENAI-CLIP, which is located at https://github.com/openai/CLIP
You can install it via their intructions.
Sorry that I haven't got time to work on this repo recently, and the part of perceptual model is still a WIP for now, which I'm not sure if it's fully functional or not. It will be updated later this year, though :)
